---
title: "Predict-Nationality"
output:
  word_document: default
  html_document: default
---
Load Packages
```{r setup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
p_load(rvest) # Packages for scraping
p_load(data.table, ggplot2, maptools, sp, tmap, classInt, geomerge) # Packages for text mining
```

```{r}
p_load("devtools")
#devtools::install_github("akondrashov96/rusmaps")
p_load(rusmaps)
```

```{r}
rus_sub_nc@data$
russia.population.plot <- tm_shape(rus_sub_nc) +
  tm_polygons(col="pop_2015",title = "Population",
  style = "fixed",
  breaks = c(0,3000000,5000000)) +
  tm_legend(position = c("right", "bottom"))#  + 
  # tm_text(text = "name", size = 0.2)
save_tmap(russia.population.plot,"Population-By-Region-Reduced.html")




```

```{r}
rus_sub_nc@data$name
write.table(rus_sub_nc@data$name, "names.csv", quote = F, row.names = F, append = F, sep = ",")
```


```{r}
ethnic.republics <- c(
"Кабардино-Балкарская Республика",
"Карачаево-Черкесская Республика",
"Республика Адыгея",
"Республика Алтай",
"Республика Башкортостан",
"Республика Бурятия",
"Республика Дагестан",
"Республика Ингушетия",
"Республика Калмыкия",
"Республика Карелия",
"Республика Коми",
"Республика Марий Эл",
"Республика Мордовия",
"Республика Саха (Якутия)",
"Республика Северная Осетия-Алания",
"Республика Татарстан",
"Республика Тыва",
"Республика Хакасия",
"Удмуртская Республика",
"Ханты-Мансийский автономный округ",
"Чеченская Республика",
"Чувашская Республика"
)
```


```{r}
rus_sub_nc$ethnic_republic <- "no"
rus_sub_nc$ethnic_republic[rus_sub_nc$name %in% ethnic.republics] <- "yes"
```


```{r}
p_load(RColorBrewer)
blups <- brewer.pal(3, "Set1")
?brewer.pal
tm_shape(rus_sub_nc) +
  tm_polygons(col="ethnic_republic",title = "Ethnic Republic") + 
  tm_legend(position = c("right", "bottom"))

save_tmap(russia.population.plot,"Maps/Ethnic-Republics.html")
```



```{r}
data(metro)
metro <- sp::spTransform(metro, proj4string(rus_sub_nc))
summary(metro)
```

```{r}
tm_shape(rus_sub_nc) +
  tm_polygons(col="pop_2015",title = "Russia's Population") +
  tm_legend(position = c("right", "bottom"))+
  tm_shape(land) +
  tm_raster(col = "trees")
tm_shape(rus_sub_nc,
         
         ) +
  tm_polygons(col="white") +
  tm_shape(land) +
  tm_raster(col = "trees")


hist(metro$pop2010)
quantile(metro$pop2010)
    tm_polygons("well_being", textNA="Non-European countries", title="Well-Being Index") +
    tm_text("iso_a3", size="AREA", root=5) + 
tm_format_Europe() +
tm_style_grey()
```




```{r}
tmap::

rus_sub_nc$pop_2016
```


```{r}
require(ggplot2)
require(maptools)
require(sp)

# Your shape file has some topology errors meaning it can't be used by 'over()'
# Use open source shapefiles from www.naturalearth.com - v. good quality
oldwd <- getwd(); tmp <- tempdir(); setwd(tmp)
url <- "http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_shp.zip"
dest <- paste(tmp,"\\tmp.zip",sep="")
download.file( url , dest )
unzip(dest)


#   Projection information for geographic data (but in decimal degrees)
projgeo <- CRS("+proj=latlong +datum=WGS84 +ellps=WGS84")


# Read in world shapefile
wld <- readShapePoly("ne_10m_admin_1_states_provinces_shp" , proj4string = projgeo)
# Subset to Russia
map <- wld[wld$admin == "Russia" , ]


# City and metro data
r.city <- world.cities[ world.cities$country.etc=="Russia" , ]
metro_outlets <- read.csv(file="e:\\r\\retail\\metro.csv",head=TRUE,sep=";")


# Assign metro outlets to city and make spatial point data frame
met <- subset( metro_outlets , select = c( "SL" , "CITY_ENGLISH" ) )
met$SL <- as.numeric( met$SL )
match <- match( met$CITY_ENGLISH , r.city$name )
coordinates( met ) <- r.city[ match , c( "long" , "lat" ) ]
proj4string( met ) <- proj4string( map )


# Assign metro outlet attribute "SL" to each region of map
# Find the average SL for each region using 'over()'
df <- over( map , met[ , "SL" ] , fn = mean , na.rm = TRUE )
map$SL <- as.numeric( df$SL )


# Convert th map into format for plotting with ggplot
map@data$id <- rownames( map@data )
map.df <- as.data.frame( map )
map.fort <- fortify( map , region = "id" )
map.gg <- join( map.fort , map.df , by = "id" )


# Plot  
p1 <-   ggplot( NULL ) + 
    geom_polygon( mapping = aes( long , lat , group = group , fill  = factor( SL ) ) , colour = "white" , data = map.gg , map = map.gg )+
    scale_x_continuous( limits = c( 20 , 180 ) )
print(p1)
```

```{r}
p_load(tmap)
data(Europe)
```


```{r}
tm_shape(Europe) + tm_borders()
```


```{r}
data(land, rivers, metro, Europe)

tm_shape(metro) + 
    tm_raster("pop2010", breaks=seq(0, 100, by=20), legend.show = FALSE)


+
tm_shape(Europe, is.master = TRUE) +
    tm_borders() +
tm_shape(rivers) +
    tm_lines(lwd="strokelwd", scale=5, legend.lwd.show = FALSE) +
tm_shape(metro) +
    tm_bubbles("pop2010", "red", border.col = "black", border.lwd=1, 
        size.lim = c(0, 11e6), sizes.legend = c(1e6, 2e6, 4e6, 6e6, 10e6), 
        title.size="Metropolitan Population") +
    tm_text("name", size="pop2010", scale=1, root=4, size.lowerbound = .6, 
        bg.color="white", bg.alpha = .75, 
        auto.placement = 1, legend.size.show = FALSE) + 
tm_format_Europe() +
tm_style_natural()
```

